import type { Metadata } from 'next';
import { DM_Sans, DM_Serif_Display, Inter } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from '@/components/theme-provider';
import Navbar from '@/components/global/Navbar';


const DMSerifDisplay = DM_Serif_Display({ subsets: ['latin'], weight: '400', style: 'normal', variable: '--dm-serif-display' });
const DMSans = DM_Sans({ subsets: ['latin'], weight: ['400', '500', '600', '700'], variable: '--dm-sans' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${DMSerifDisplay.variable} ${DMSans.variable}`}>
        <ThemeProvider attribute='class' defaultTheme='system' enableSystem disableTransitionOnChange>
          <Navbar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
